# Generated by Django 5.1.1 on 2024-09-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_ispublished_alter_movie_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='detailed_description',
            field=models.TextField(default='geçici açıklam', verbose_name='Detaylar'),
            preserve_default=False,
        ),
    ]
