# Generated by Django 5.1.1 on 2024-09-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_detailed_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='detailed_description',
        ),
    ]
