# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_checkbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(502, 418)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnHChoose = QtWidgets.QPushButton(self.centralwidget)
        self.btnHChoose.setGeometry(QtCore.QRect(30, 150, 171, 71))
        self.btnHChoose.setObjectName("btnHChoose")
        self.lblHResult = QtWidgets.QLabel(self.centralwidget)
        self.lblHResult.setGeometry(QtCore.QRect(30, 220, 171, 91))
        self.lblHResult.setText("")
        self.lblHResult.setObjectName("lblHResult")
        self.GroupHobiler = QtWidgets.QGroupBox(self.centralwidget)
        self.GroupHobiler.setGeometry(QtCore.QRect(10, 10, 211, 161))
        self.GroupHobiler.setObjectName("GroupHobiler")
        self.widget = QtWidgets.QWidget(self.GroupHobiler)
        self.widget.setGeometry(QtCore.QRect(20, 20, 171, 121))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbSinema = QtWidgets.QCheckBox(self.widget)
        self.cbSinema.setObjectName("cbSinema")
        self.verticalLayout.addWidget(self.cbSinema)
        self.cbOyun = QtWidgets.QCheckBox(self.widget)
        self.cbOyun.setObjectName("cbOyun")
        self.verticalLayout.addWidget(self.cbOyun)
        self.cbSpor = QtWidgets.QCheckBox(self.widget)
        self.cbSpor.setObjectName("cbSpor")
        self.verticalLayout.addWidget(self.cbSpor)
        self.GroupDersler = QtWidgets.QGroupBox(self.centralwidget)
        self.GroupDersler.setGeometry(QtCore.QRect(210, 10, 211, 161))
        self.GroupDersler.setObjectName("GroupDersler")
        self.layoutWidget = QtWidgets.QWidget(self.GroupDersler)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 171, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbWebTasarim = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbWebTasarim.setObjectName("cbWebTasarim")
        self.verticalLayout_2.addWidget(self.cbWebTasarim)
        self.cbProgramlama = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbProgramlama.setObjectName("cbProgramlama")
        self.verticalLayout_2.addWidget(self.cbProgramlama)
        self.cbVeriTabani = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbVeriTabani.setObjectName("cbVeriTabani")
        self.verticalLayout_2.addWidget(self.cbVeriTabani)
        self.btnDChoose = QtWidgets.QPushButton(self.centralwidget)
        self.btnDChoose.setGeometry(QtCore.QRect(230, 150, 171, 71))
        self.btnDChoose.setObjectName("btnDChoose")
        self.lblDResult = QtWidgets.QLabel(self.centralwidget)
        self.lblDResult.setGeometry(QtCore.QRect(230, 220, 171, 91))
        self.lblDResult.setText("")
        self.lblDResult.setObjectName("lblDResult")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 502, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnHChoose.setText(_translate("MainWindow", "seçilenleri al"))
        self.GroupHobiler.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbSinema.setText(_translate("MainWindow", "Sinema"))
        self.cbOyun.setText(_translate("MainWindow", "Bilgisayar oyunu"))
        self.cbSpor.setText(_translate("MainWindow", "Spor"))
        self.GroupDersler.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbWebTasarim.setText(_translate("MainWindow", "Web tasarım"))
        self.cbProgramlama.setText(_translate("MainWindow", "Programlama"))
        self.cbVeriTabani.setText(_translate("MainWindow", "Veri tabanı"))
        self.btnDChoose.setText(_translate("MainWindow", "seçilenleri al"))
