# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_radiobutton.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(445, 317)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupUlke = QtWidgets.QGroupBox(self.centralwidget)
        self.groupUlke.setGeometry(QtCore.QRect(40, 50, 141, 111))
        self.groupUlke.setObjectName("groupUlke")
        self.layoutWidget = QtWidgets.QWidget(self.groupUlke)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 141, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioTurkiye = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioTurkiye.setObjectName("radioTurkiye")
        self.verticalLayout.addWidget(self.radioTurkiye)
        self.radioAlmanya = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioAlmanya.setObjectName("radioAlmanya")
        self.verticalLayout.addWidget(self.radioAlmanya)
        self.radioJaponya = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioJaponya.setObjectName("radioJaponya")
        self.verticalLayout.addWidget(self.radioJaponya)
        self.groupEgitim = QtWidgets.QGroupBox(self.centralwidget)
        self.groupEgitim.setGeometry(QtCore.QRect(230, 50, 141, 111))
        self.groupEgitim.setObjectName("groupEgitim")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupEgitim)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 10, 141, 101))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioIlkokul = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioIlkokul.setObjectName("radioIlkokul")
        self.verticalLayout_2.addWidget(self.radioIlkokul)
        self.radioLise = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioLise.setObjectName("radioLise")
        self.verticalLayout_2.addWidget(self.radioLise)
        self.radioUniversite = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioUniversite.setObjectName("radioUniversite")
        self.verticalLayout_2.addWidget(self.radioUniversite)
        self.radioYuksekLsans = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioYuksekLsans.setObjectName("radioYuksekLsans")
        self.verticalLayout_2.addWidget(self.radioYuksekLsans)
        self.lbl_country = QtWidgets.QLabel(self.centralwidget)
        self.lbl_country.setGeometry(QtCore.QRect(40, 180, 141, 31))
        self.lbl_country.setText("")
        self.lbl_country.setObjectName("lbl_country")
        self.lbl_edu = QtWidgets.QLabel(self.centralwidget)
        self.lbl_edu.setGeometry(QtCore.QRect(230, 180, 141, 31))
        self.lbl_edu.setText("")
        self.lbl_edu.setObjectName("lbl_edu")
        self.btn_country = QtWidgets.QPushButton(self.centralwidget)
        self.btn_country.setGeometry(QtCore.QRect(40, 230, 141, 41))
        self.btn_country.setObjectName("btn_country")
        self.btn_edu = QtWidgets.QPushButton(self.centralwidget)
        self.btn_edu.setGeometry(QtCore.QRect(230, 230, 141, 41))
        self.btn_edu.setObjectName("btn_edu")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 445, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupUlke.setTitle(_translate("MainWindow", "Ülkeler"))
        self.radioTurkiye.setText(_translate("MainWindow", "Türkiye"))
        self.radioAlmanya.setText(_translate("MainWindow", "Almanya"))
        self.radioJaponya.setText(_translate("MainWindow", "Japonya"))
        self.groupEgitim.setTitle(_translate("MainWindow", "Eğitim Düzeyleri"))
        self.radioIlkokul.setText(_translate("MainWindow", "İlkokul"))
        self.radioLise.setText(_translate("MainWindow", "Lise"))
        self.radioUniversite.setText(_translate("MainWindow", "Üniversite"))
        self.radioYuksekLsans.setText(_translate("MainWindow", "Yüksek lisans"))
        self.btn_country.setText(_translate("MainWindow", "Ülke Seçimi"))
        self.btn_edu.setText(_translate("MainWindow", "Eğitim Seçimi"))
